openapi: 3.0.0
info:
  title: 01_TEST_REST_API
  version: 1.0.0
servers:
  - url: http://testphp.vulnweb.com
paths:
  /:
    get:
      tags:
        - default
      summary: testphp
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
