#test
name: OWASP ZAP API 3

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Newman
        run: |
          sudo apt update
          sudo apt install nodejs npm -y
          nodejs --version

          npm install -g newman
          npm install -g newman-reporter-html
          npm install -g newman-reporter-htmlextra
          newman -h
          
          npm i -g postman-to-openapi
          p2o -h
          
      - name: Docker Images ZAP Scan
        run: docker pull owasp/zap2docker-stable 
      - name: Start Scan
        run: |
          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t TEST_REST_API.yml -f openapi
