#test
name: OWASP ZAP API 3

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: DIR
        run: ls -la

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
              
        with:
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'TEST_REST_API.yml'
          rules_file_name: '.zap/rules.tsv'
      - name: Report
        uses: actions/upload-artifact@v1
        with:
          name: zap-report
          path: report_html.html
