#test
name: OWASP ZAP API 3

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: DIR
        run: ls -la ./zap/wrk

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
              
        with:
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 01_TEST_REST_API.postman_collection.json
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
