name: OWASP ZAP API

on: [push]
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'https://www.example.com/openapi.json'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
