#test
name: OWASP ZAP API 3

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DIR
        run: echo ${pwd}
      - name: Docker Images ZAP Scan
        run: docker pull owasp/zap2docker-stable 
      - name: Start Scan
        run: |
          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t TEST_REST_API.yml -f openapi
